name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm install

      - name: Prettier check
        run: npm run prettier --check .

      - name: Type check
        run: npm run tsc --noEmit

      - name: Build (Next.js)
        run: npm run build
